#!/usr/bin/env bash
# validate-harness.sh — validate agent definitions and skill files generated by harness
# Usage: bash scripts/validate-harness.sh [agents-dir] [skills-dir]
#   agents-dir  default: .claude/agents
#   skills-dir  default: .claude/skills
set -euo pipefail

AGENTS_DIR="${1:-.claude/agents}"
SKILLS_DIR="${2:-.claude/skills}"

ERRORS=0
WARNINGS=0

ok()   { echo "  ✓ $*"; }
err()  { echo "  ✗ $*" >&2; ((ERRORS++)); }
warn() { echo "  ⚠ $*"; ((WARNINGS++)); }
section() { echo ""; echo "=== $* ==="; }

# ── Agent Definition Validation ─────────────────────────────────────────────

section "Agent Definitions: ${AGENTS_DIR}"

if [ ! -d "${AGENTS_DIR}" ]; then
  warn "Agents directory not found: ${AGENTS_DIR}"
else
  AGENT_COUNT=0
  for agent_file in "${AGENTS_DIR}"/*.md; do
    [ -f "${agent_file}" ] || continue
    name="$(basename "${agent_file}" .md)"
    echo ""
    echo "  Agent: ${name}"
    ((AGENT_COUNT++))

    # Check required frontmatter fields
    if grep -q "^---" "${agent_file}"; then
      ok "Has frontmatter"
    else
      err "Missing frontmatter (---)"
    fi

    if grep -q "^name:" "${agent_file}"; then
      ok "Has name field"
    else
      err "Missing 'name:' in frontmatter"
    fi

    if grep -q "^description:" "${agent_file}"; then
      ok "Has description field"
    else
      err "Missing 'description:' in frontmatter"
    fi

    # Check required sections
    for section_name in "Core Responsibilities" "Input Protocol" "Output Protocol"; do
      if grep -q "## ${section_name}" "${agent_file}"; then
        ok "Section: ${section_name}"
      else
        warn "Missing recommended section: ${section_name}"
      fi
    done

    # Check file length
    LINE_COUNT=$(wc -l < "${agent_file}")
    if [ "${LINE_COUNT}" -gt 200 ]; then
      warn "Agent definition is ${LINE_COUNT} lines — consider condensing"
    else
      ok "File length: ${LINE_COUNT} lines"
    fi
  done

  if [ "${AGENT_COUNT}" -eq 0 ]; then
    warn "No .md files found in ${AGENTS_DIR}"
  else
    ok "Total agents found: ${AGENT_COUNT}"
  fi
fi

# ── Skill Validation ─────────────────────────────────────────────────────────

section "Skills: ${SKILLS_DIR}"

if [ ! -d "${SKILLS_DIR}" ]; then
  warn "Skills directory not found: ${SKILLS_DIR}"
else
  SKILL_COUNT=0
  for skill_dir in "${SKILLS_DIR}"/*/; do
    [ -d "${skill_dir}" ] || continue
    skill_name="$(basename "${skill_dir}")"
    skill_md="${skill_dir}SKILL.md"
    echo ""
    echo "  Skill: ${skill_name}"
    ((SKILL_COUNT++))

    if [ ! -f "${skill_md}" ]; then
      err "Missing SKILL.md in ${skill_dir}"
      continue
    fi
    ok "SKILL.md present"

    # Validate frontmatter name matches directory
    FM_NAME=$(grep "^name:" "${skill_md}" | head -1 | sed 's/name: *//' | tr -d '"' | xargs)
    if [ "${FM_NAME}" = "${skill_name}" ]; then
      ok "name matches directory: ${FM_NAME}"
    else
      err "name mismatch: frontmatter='${FM_NAME}' dir='${skill_name}'"
    fi

    # Description length
    DESC=$(awk '/^description:/,/^[a-z]/' "${skill_md}" | grep -v "^[a-z]" | sed 's/description: *//' | tr -d '>' | tr '\n' ' ' | xargs)
    DESC_LEN=${#DESC}
    if [ "${DESC_LEN}" -gt 1024 ]; then
      err "Description too long: ${DESC_LEN} chars (max 1024)"
    elif [ "${DESC_LEN}" -lt 50 ]; then
      warn "Description may be too short: ${DESC_LEN} chars"
    else
      ok "Description length: ${DESC_LEN} chars"
    fi

    # Check recommended sections
    for section_name in "When to use this skill" "Instructions" "Examples" "Best practices"; do
      if grep -q "## ${section_name}" "${skill_md}"; then
        ok "Section: ${section_name}"
      else
        warn "Missing recommended section: ${section_name}"
      fi
    done

    # File length
    LINE_COUNT=$(wc -l < "${skill_md}")
    if [ "${LINE_COUNT}" -gt 500 ]; then
      warn "SKILL.md is ${LINE_COUNT} lines — move details to references/"
    else
      ok "File length: ${LINE_COUNT} lines"
    fi
  done

  if [ "${SKILL_COUNT}" -eq 0 ]; then
    warn "No skill directories found in ${SKILLS_DIR}"
  else
    ok "Total skills found: ${SKILL_COUNT}"
  fi
fi

# ── Summary ──────────────────────────────────────────────────────────────────

section "Summary"
echo "  Errors:   ${ERRORS}"
echo "  Warnings: ${WARNINGS}"
echo ""

if [ "${ERRORS}" -gt 0 ]; then
  echo "Validation FAILED — fix ${ERRORS} error(s) before using this harness."
  exit 1
else
  echo "Validation PASSED${WARNINGS:+ (${WARNINGS} warning(s))}."
  exit 0
fi
