#!/usr/bin/env python3
"""Validate AGENTS.md hierarchy generated by deepinit."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys


PARENT_RE = re.compile(r"<!--\s*Parent:\s*(.*?)\s*-->")
DEFAULT_EXCLUDES = {
    ".git",
    "node_modules",
    "dist",
    "build",
    "coverage",
    ".next",
    ".nuxt",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".venv",
    "venv",
    "env",
    ".omc",
    ".omx",
    ".survey",
    ".codex",
    ".claude",
    ".gemini",
    ".opencode",
    ".ouroboros",
}


def is_excluded(path: Path, root: Path) -> bool:
    try:
        parts = path.relative_to(root).parts
    except ValueError:
        return True
    if not parts:
        return False
    if parts[0] == ".agent-skills":
        return False
    return any(part in DEFAULT_EXCLUDES for part in parts)


def find_agents_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for path in root.rglob("AGENTS.md"):
        if not is_excluded(path, root):
            files.append(path)
    return sorted(files)


def validate_file(path: Path, root: Path, strict: bool) -> tuple[list[str], list[str]]:
    rel = path.relative_to(root).as_posix()
    text = path.read_text(encoding="utf-8")
    errors: list[str] = []
    warnings: list[str] = []

    parent_matches = PARENT_RE.findall(text)
    if path.parent == root:
        if parent_matches:
            errors.append(f"{rel}: root AGENTS.md must not have Parent tag")
    else:
        if not parent_matches:
            message = f"{rel}: missing Parent tag"
            (errors if strict else warnings).append(message)
        elif len(parent_matches) > 1:
            errors.append(f"{rel}: multiple Parent tags")
        else:
            parent = (path.parent / parent_matches[0]).resolve()
            if not parent.exists():
                errors.append(f"{rel}: Parent does not resolve: {parent_matches[0]}")
            elif parent.name != "AGENTS.md":
                errors.append(f"{rel}: Parent target is not AGENTS.md: {parent_matches[0]}")

    if "<!-- MANUAL:" not in text:
        message = f"{rel}: missing MANUAL preservation marker"
        (errors if strict else warnings).append(message)

    return errors, warnings


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", nargs="?", default=".", type=Path)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="fail when existing AGENTS.md files lack Parent or MANUAL markers",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    files = find_agents_files(root)
    errors: list[str] = []
    warnings: list[str] = []
    for path in files:
        file_errors, file_warnings = validate_file(path, root, args.strict)
        errors.extend(file_errors)
        warnings.extend(file_warnings)

    if errors:
        for error in errors:
            print(f"[FAIL] {error}", file=sys.stderr)
        return 1

    for warning in warnings:
        print(f"[WARN] {warning}")
    print(f"AGENTS hierarchy validation: PASS ({len(files)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
